services:
  postgresdb:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sandy
      POSTGRES_PASSWORD: password 
      POSTGRES_ADMIN: admin

    volumes:
      - "postgres_data:/var/lib/prostgresql/data"

volumes:
  postgres_data:
